[build]
  command = "pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "10.15.1"

# Production branch (main)
[[context.production]]
  branch = "main"

# Staging branch
[[context.staging]]
  branch = "staging"

# Preview deployments (all other branches and PRs)
[[context.deploy-preview]]
  branch = "*"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

